### ISSUE TITLE
undefined method `use' for MultiJson:Module (NoMethodError)

### ISSUE THREAD

**Issue by camfowler** [crashlog/crashlog#3]
Rails 3.2.2, Ruby 1.9.3p194

I added the gem to my Gemfile, and added the initialize script. Direct copy and paste.
Error on starting up the rails app.

``` log
/Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/crashlog-1.0.1/lib/crash_log/reporter.rb:22:in `initialize': undefined method `use' for MultiJson:Module (NoMethodError)
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/crashlog-1.0.1/lib/crash_log.rb:87:in `new'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/crashlog-1.0.1/lib/crash_log.rb:87:in `configure'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/crashlog-1.0.1/lib/crash_log/railtie.rb:9:in `block in <class:Railtie>'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:34:in `call'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:42:in `each'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `run'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `each'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/application.rb:136:in `initialize!'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/cam/projects/nzpost/kiwibank-locator-direct/config/environment.rb:5:in `<top (required)>'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/application.rb:103:in `require'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/application.rb:103:in `require_environment!'
    from /Users/cam/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.2/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by ivanvanderbyl** [comment]
Looks like a standard case of an outdated MultiJson — I'll update it shortly to require a newer version. Until then you can add this to your Gemfile:

``` ruby
gem 'multi_json',  '~> 1.3.6'
```

**Comment by ivanvanderbyl** [comment]
I've just pushed 1.0.2 which should fix this.

http://rubygems.org/gems/crashlog
