### ISSUE TITLE
SSL peer verification does not seem to work (JRuby)

### ISSUE THREAD

**Issue by Overbryd** [crashlog/crashlog#6]
Hi,

after removing activesupport, therefore making crashlog usable for the first time in my application, I still could not submit exceptions to your service.

I invested some time to investigate the issue.
The first problem is, that `Reporter#notify` swallows exceptions:

``` ruby
def notify(payload)
  return if dry_run?

  response = post(endpoint, MultiJson.encode({:payload => payload}))
  @response = response
  report_result(response.body)
  response.success?
rescue => e
  # log_exception e
  error("Sending exception failed due to a connectivity issue")
  # I added this line to find out about the issue
  raise e
  nil
end
```

After that I found out that the issue was a `Faraday::Error::ConnectionFailed: certificate verify failed`:

```
E, [2012-10-16T15:29:50.430000 #25829] ERROR -- : ** [CrashLog] Sending exception failed due to a connectivity issue
E, [2012-10-16T15:29:50.431000 #25829] ERROR -- : ** [CrashLog] Failed to deliver notification to CrashLog collector
E, [2012-10-16T15:29:50.431000 #25829] ERROR -- : Faraday::Error::ConnectionFailed: certificate verify failed
E, [2012-10-16T15:29:50.432000 #25829] ERROR -- : org/jruby/ext/openssl/SSLSocket.java:156:in `connect'
E, [2012-10-16T15:29:50.432000 #25829] ERROR -- : /Volumes/Home/.rbenv/versions/jruby-1.7.0-RC1/lib/ruby/1.9/net/http.rb:799:in `connect'
E, [2012-10-16T15:29:50.433000 #25829] ERROR -- : org/jruby/ext/timeout/Timeout.java:124:in `timeout'
E, [2012-10-16T15:29:50.433000 #25829] ERROR -- : /Volumes/Home/.rbenv/versions/jruby-1.7.0-RC1/lib/ruby/1.9/net/http.rb:799:in `connect'
E, [2012-10-16T15:29:50.433000 #25829] ERROR -- : /Volumes/Home/.rbenv/versions/jruby-1.7.0-RC1/lib/ruby/1.9/net/http.rb:755:in `do_start'
E, [2012-10-16T15:29:50.434000 #25829] ERROR -- : /Volumes/Home/.rbenv/versions/jruby-1.7.0-RC1/lib/ruby/1.9/net/http.rb:744:in `start'
E, [2012-10-16T15:29:50.434000 #25829] ERROR -- : /Volumes/Home/.rbenv/versions/jruby-1.7.0-RC1/lib/ruby/1.9/net/http.rb:1292:in `request'
```

A naive fix was to disable ssl verification in Faraday `Reporter#connection`:

``` ruby
def connection
  @connection ||= begin
    Faraday.new(:url => url, :ssl => { :verify => false }) do |faraday|
      faraday.request :hmac_authentication, config.api_key, config.secret, {:service_id => config.service_name}
      faraday.adapter(adapter)
      faraday.request :url_encoded
      # faraday.response                :logger
      # faraday.ssl[:verify]            = false
    end
  end
end
```

And then it worked:

```
I, [2012-10-16T15:16:48.429000 #21954]  INFO -- : ** [CrashLog] Event sent to CrashLog.io
I, [2012-10-16T15:16:48.432000 #21954]  INFO -- : ** [CrashLog] Event URL: http://crashlog.io/locate/a90117d0-f9c1-012f-c036-0016671d4063
```

What shall we do about this?
Obviously the SSL support seems to be broken.
Can you make SSL verification optional?

Cheers, Lukas

**Comment by ivanvanderbyl** [comment]
OK so after taking a closer look at this, and at your previous PR, It looks like even through you removed ActiveSupport it was still available due to the requirement on Rails for testing as such all tests were still passing. I don't think this is ideal so I'm going to remove all Rails specific tests and compile a script which can test against all versions of Rails individually. 

Additionally I've added a `development_mode` config option to re-raise swallowed exceptions as you were saying above, the reason we do this is so we don't break people apps if we fail at something.

I've also added proper SSL CA verification with a packaged bundle.

I'll release an update later today.

**Comment by wolfeidau** [comment]
You mite want to deliver complete the chain of certificates delivered by your web server.

For nginx this is quite simple, download each of the certs which form the chain and concatenate them into one .crt file.

The chain presented by crashlog is as follows, some clients may be missing the certificate listed at 2, which would result in them not being able to complete the chain of trust.

```
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.crashlog.io
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=PositiveSSL CA 2
 1 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=PositiveSSL CA 2
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
```

To verify this is satisfactory for the client I would be interested to see the output of showcerts option to openssl s_client, this option can be used to show the whole chain.

```
openssl s_client -host crashlog.io -port 443 -showcerts
```

Hope that helps.

**Comment by ivanvanderbyl** [comment]
Thanks @wolfeidau — I'm looking at packaging a CA bundle and pointing Faraday to it. Seems to be the preferred approach.

I'm currently refactoring the test suite, trying to figure out a solid way to test multiple versions of Rails specifically without requiring any of Rails as a dependency.

**Comment by ivanvanderbyl** [comment]
Hey @Overbryd I've added a few options to Configuration which should fix this now. We still need to do more testing before pushing this out, but at the moment it should work if you point bundler to master.

By default we now package a CA bundle and point Faraday to it when using SSL.
